# Generated by Django 2.0.4 on 2018-04-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.TextField()),
                ('driver_position', models.PositiveIntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='F1ChampionshipYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship_year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.TextField(unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1OverTheYears.Country', to_field='country')),
            ],
        ),
        migrations.AddField(
            model_name='driverstandings',
            name='championship_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1OverTheYears.F1ChampionshipYears', to_field='championship_year'),
        ),
        migrations.AddField(
            model_name='driverstandings',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1OverTheYears.Country', to_field='country'),
        ),
        migrations.AddField(
            model_name='driverstandings',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1OverTheYears.Manufacturer', to_field='manufacturer_name'),
        ),
    ]
